language: python
dist: bionic

python:
  - "2.7"
  - "3.6"

cache:
  directories:
    - $GDALINST
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild
  matrix:
    - GDALVERSION="3.0.0rc2" PROJVERSION="6.2.1RC1"
    - GDALVERSION="1.11.5" PROJVERSION="4.8.0"
    - GDALVERSION="2.0.3" PROJVERSION="4.9.3"
    - GDALVERSION="2.1.4" PROJVERSION="4.9.3"
    - GDALVERSION="2.2.4" PROJVERSION="4.9.3"
    - GDALVERSION="2.3.3" PROJVERSION="4.9.3"
    - GDALVERSION="2.4.4" PROJVERSION="4.9.3"
    - GDALVERSION="3.0.4" PROJVERSION="6.2.1"
    - GDALVERSION="master" PROJVERSION="6.3.1"

matrix:
  allow_failures:
    - env: GDALVERSION="master" PROJVERSION="6.3.1"

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
    - libsqlite3-dev
    - sqlite3

before_install:
  - python -m pip install -U pip
  - . ./scripts/travis_proj_install.sh
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj
  - gdal-config --version
  - python -m pip wheel -r requirements-dev.txt
  - python -m pip install -r requirements-dev.txt
  - python -m pip install wheel coveralls>=1.1 --upgrade

install:
  - if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $(gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi  - "python -m pip wheel -r requirements-dev.txt"
  - "python -m pip install -r requirements-dev.txt"
  - "GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install --upgrade --force-reinstall --no-use-pep517 -e .[test]"
  - fio --version
  - gdal-config --version
  - fio --gdal-version

script:
  - python -m pytest -m "not wheel" --cov fiona --cov-report term-missing

after_script:
  - python setup.py clean

after_success:
  - coveralls || echo "!! intermittent coveralls failure"

before_cache:
  - if [ "$GDALVERSION" = "trunk" ]; then rm -rf $GDALINST/gdal-$GDALVERSION; fi
