# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS CI

on: [push, pull_request]

env:
    MAKEFLAGS: "-j 4 -s"
    CXXFLAGS: "-O0"
    CFLAGS: "-O0"

    
jobs:
  build:

    runs-on: macos-10.15
    strategy:
      matrix:
        config:
          - {python-version: 3.6, GDALVERSION: "1.11.5", PROJVERSION: "4.9.3"}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}

    - name: Set env variables
      run: |
        echo "export GDALINST=$HOME/gdalinstall" > ~/.bashrc
        echo "export GDALBUILD=$HOME/gdalbuild" > ~/.bashrc
        echo "export PROJINST=$HOME/gdalinstall" > ~/.bashrc
        echo "export PROJBUILD=$HOME/projbuild" > ~/.bashrc
        echo "export GDALVERSION=${{matrix.config.GDALVERSION}}" > ~/.bashrc
        echo "export PROJVERSION=${{matrix.config.PROJVERSION}}" > ~/.bashrc
        echo "export TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE" > ~/.bashrc
        echo "export TRAVIS_OS_NAME=osx" > ~/.bashrc
        source ~/.bashrc
        echo "export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal" > ~/.bashrc
        echo "export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj" > ~/.bashrc
        echo "export PATH=$GDALINST/gdal-$GDALVERSION/bin:$GDALINST/proj-$PROJVERSION/bin:$PATH" > ~/.bashrc
        echo "export DYLD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$GDALINST/proj-$PROJVERSION/lib:$DYLD_LIBRARY_PATH" > ~/.bashrc

    - name: Install brew packages
      run: |
        brew install expat libspatialite sqlite geos

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python -m pip install coveralls>=1.1 --upgrade
        
    - name: Build PROJ
      run: |
        source ~/.bashrc
        chmod +x scripts/travis_proj_install.sh && ./scripts/travis_proj_install.sh
        
    - name: Build GDAL
      run: |
        source ~/.bashrc
        chmod +x scripts/travis_gdal_install.sh && ./scripts/travis_gdal_install.sh
        gdal-config --version

    - name: Build Fiona
      run: |
        source ~/.bashrc
        if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
        GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install -v -v -v --no-deps --force-reinstall --no-use-pep517 -e .
        fio --version
        fio --gdal-version


    - name: Test with pytest
      run: |
        source ~/.bashrc
        python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
