name: Windows CI

on: [push, pull_request]

jobs:
  build:
    name: GDAL ${{ matrix.GDALVERSION }}
    runs-on: [windows-2019]
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.6
            GDAL_VERSION: 2.0.3
            GIS_INTERNALS: release-1911-x64-gdal-3-0-4-mapserver-7-4-3.zip
            GIS_INTERNALS_LIBS: release-1911-x64-gdal-3-0-4-mapserver-7-4-3-libs.zip

    env:
      GIS_INTERNALS: ${{ matrix.GIS_INTERNALS }}
      GIS_INTERNALS_LIBS: ${{ matrix.GIS_INTERNALS_LIBS }}
      # PROJVERSION: ${{ matrix.PROJVERSION }}
      # GDALVERSION: ${{ matrix.GDALVERSION }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Set env variables
        run: |
          echo "C:\\gdal\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "GDAL_DATA=C:\\gdal\\bin\\gdal-data" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download GIS_INTERNALS
        run: |
          echo $env:GIS_INTERNALS
          curl http://download.gisinternals.com/sdk/downloads/$GIS_INTERNALS --output gdalbin.zip
          7z x gdalbin.zip -o C:\gdal
          curl http://download.gisinternals.com/sdk/downloads/$GIS_INTERNALS_LIBS --output gdallibs.zip
          7z x gdallibs.zip -o C:\gdal

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements-ci.txt
          python -m pip wheel -r requirements-dev.txt
          python -m pip install -r requirements-dev.txt

      - name: Print Environment
        continue-on-error: ${{ matrix.GDALVERSION == 'master' }}
        run: |
          echo "python -m pip freeze"
          python -m pip freeze

          echo %PATH%